### ISSUE TITLE
Update throw an exception

### ISSUE THREAD

**Issue by gynet** [keeweb/keeweb#1158]
**Describe the bug**
Update keeweb by click the "Check for udpate" , saw an exception error, this issue happend on both Windows and Mac

** Uncaught Exception**
/Users/xxx/Library/Application Support/KeeWeb/app.asar/app.js:506
}.call(this, exports, require, module, __filename, __dirname); });
                                                            ^

SyntaxError: missing ) after argument list
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:660:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)

**Comment by antelle** [comment]
Hi! From which version did you upgrade! I noticed it when upgrading from 1.7, but I can't repeat it on 1.8.

**Comment by gynet** [comment]
Not sure, but should be either 1.8.0 => 1.8.1 or 1.7.8 => 1.8.1

**Comment by antelle** [comment]
Let's see if it repeats. For me it happened on 1.7.8 => 1.8.0, but not 1.8.0 => 1.8.1.

**Comment by antelle** [comment]
Tried two updates after 1.8.0, seems to be working well. Let's wait a bit and close this if there are no new reports after 1.8.

**Comment by gynet** [comment]
Got this issue repro with verison n-1 to n. 
![image](https://user-images.githubusercontent.com/2174522/56702520-4559b280-66b9-11e9-8362-9f4b73f677db.png)

**Comment by gynet** [comment]
I am on windows

**Comment by Avik-B** [comment]
I am having this same issue for quite some time.
![image](https://user-images.githubusercontent.com/2894306/56707087-24cf3e00-6735-11e9-95c0-10e57e7911d7.png)


I am on Windows 10 N
version 1809
