### ISSUE TITLE
electron /usr/lib/keeweb/app.asar/native-module-host.js keeps crashing

### ISSUE THREAD

**Issue by dr4Ke** [keeweb/keeweb#1625]
**Describe the bug**

Every 3-4 seconds, systemd tells me there has been a coredump for electron.

**To Reproduce**
1. Just launch keeweb on a gnome3 linux.
2. Watch the crash loop with `journalctl -f`

**Expected behavior**
No crash.

**Screenshots**
Extract from journalctl log:
```
nov. 13 15:47:24 B6NC9S2-CDR systemd-coredump[170870]: Removed old coredump core.electron.1001.8f36a568eba34dd8908eaaf04a6b139b.170789.1605278841000000.zst.
nov. 13 15:47:25 B6NC9S2-CDR systemd-coredump[170870]: [🡕] Process 170861 (electron) of user 1001 dumped core.
                                                       
                                                       Stack trace of thread 170861:
                                                       #0  0x0000562b79bf60f8 uv_run (electron + 0x78a40f8)
                                                       #1  0x0000562b73f3bc28 n/a (electron + 0x1be9c28)
                                                       #2  0x0000562b73dbc588 n/a (electron + 0x1a6a588)
                                                       #3  0x00007f157f2a5152 __libc_start_main (libc.so.6 + 0x28152)
                                                       #4  0x0000562b73dbc32e _start (electron + 0x1a6a32e)
                                                       
                                                       Stack trace of thread 170865:
                                                       #0  0x00007f15832df6a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                                       #1  0x0000562b79c0317a uv_cond_wait (electron + 0x78b117a)
                                                       #2  0x0000562b79b3f572 n/a (electron + 0x77ed572)
                                                       #3  0x0000562b79b3ce4f n/a (electron + 0x77eae4f)
                                                       #4  0x00007f15832d93e9 start_thread (libpthread.so.0 + 0x93e9)
                                                       #5  0x00007f157f37d293 __clone (libc.so.6 + 0x100293)
                                                       
                                                       Stack trace of thread 170863:
                                                       #0  0x00007f15832df9c8 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf9c8)
                                                       #1  0x0000562b76455043 n/a (electron + 0x4103043)
                                                       #2  0x0000562b76455732 n/a (electron + 0x4103732)
                                                       #3  0x0000562b76430cba n/a (electron + 0x40decba)
                                                       #4  0x0000562b76431422 n/a (electron + 0x40df422)
                                                       #5  0x0000562b7643125a n/a (electron + 0x40df25a)
                                                       #6  0x0000562b76457e2a n/a (electron + 0x4105e2a)
                                                       #7  0x00007f15832d93e9 start_thread (libpthread.so.0 + 0x93e9)
                                                       #8  0x00007f157f37d293 __clone (libc.so.6 + 0x100293)
                                                       
                                                       Stack trace of thread 170862:
                                                       #0  0x00007f157f37d5de epoll_wait (libc.so.6 + 0x1005de)
                                                       #1  0x00007f1581acc9e6 n/a (libevent-2.1.so.7 + 0x2f9e6)
                                                       #2  0x00007f1581ac18c9 event_base_loop (libevent-2.1.so.7 + 0x248c9)
                                                       #3  0x0000562b7646565e n/a (electron + 0x411365e)
                                                       #4  0x0000562b7641e9e4 n/a (electron + 0x40cc9e4)
                                                       #5  0x0000562b763f5fb7 n/a (electron + 0x40a3fb7)
                                                       #6  0x0000562b764292cb n/a (electron + 0x40d72cb)
                                                       #7  0x0000562b7643704b n/a (electron + 0x40e504b)
                                                       #8  0x0000562b76457e2a n/a (electron + 0x4105e2a)
                                                       #9  0x00007f15832d93e9 start_thread (libpthread.so.0 + 0x93e9)
                                                       #10 0x00007f157f37d293 __clone (libc.so.6 + 0x100293)
                                                       
                                                       Stack trace of thread 170866:
                                                       #0  0x00007f15832df6a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                                       #1  0x0000562b79c0317a uv_cond_wait (electron + 0x78b117a)
                                                       #2  0x0000562b79b3f572 n/a (electron + 0x77ed572)
                                                       #3  0x0000562b79b3ce4f n/a (electron + 0x77eae4f)
                                                       #4  0x00007f15832d93e9 start_thread (libpthread.so.0 + 0x93e9)
                                                       #5  0x00007f157f37d293 __clone (libc.so.6 + 0x100293)
                                                       
                                                       Stack trace of thread 170864:
                                                       #0  0x00007f157f37d5de epoll_wait (libc.so.6 + 0x1005de)
                                                       #1  0x0000562b79c06068 n/a (electron + 0x78b4068)
                                                       #2  0x0000562b79bf6094 uv_run (electron + 0x78a4094)
                                                       #3  0x0000562b79b3f344 n/a (electron + 0x77ed344)
                                                       #4  0x00007f15832d93e9 start_thread (libpthread.so.0 + 0x93e9)
                                                       #5  0x00007f157f37d293 __clone (libc.so.6 + 0x100293)
                                                       
                                                       Stack trace of thread 170867:
                                                       #0  0x00007f15832df6a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                                       #1  0x0000562b79c0317a uv_cond_wait (electron + 0x78b117a)
                                                       #2  0x0000562b79b3f572 n/a (electron + 0x77ed572)
                                                       #3  0x0000562b79b3ce4f n/a (electron + 0x77eae4f)
                                                       #4  0x00007f15832d93e9 start_thread (libpthread.so.0 + 0x93e9)
                                                       #5  0x00007f157f37d293 __clone (libc.so.6 + 0x100293)
                                                       
                                                       Stack trace of thread 170868:
                                                       #0  0x00007f15832e2014 do_futex_wait.constprop.0 (libpthread.so.0 + 0x12014)
                                                       #1  0x00007f15832e2118 __new_sem_wait_slow.constprop.0 (libpthread.so.0 + 0x12118)
                                                       #2  0x0000562b79c02f8c uv_sem_wait (electron + 0x78b0f8c)
                                                       #3  0x0000562b79bb150b n/a (electron + 0x785f50b)
                                                       #4  0x00007f15832d93e9 start_thread (libpthread.so.0 + 0x93e9)
                                                       #5  0x00007f157f37d293 __clone (libc.so.6 + 0x100293)
nov. 13 15:47:25 B6NC9S2-CDR systemd[1]: systemd-coredump@7366-170869-0.service: Succeeded.

```

**Environment**

```
KeeWeb v1.15.5 (62ea6312, 2020-08-17)
Environment: electron v10.1.3
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.15.5 Chrome/85.0.4183.121 Electron/10.1.3 Safari/537.36
```
I'm on archlinux with gnome 3.38.1 on a X11 display and 5.8.14-arch1-1 kernel.

**Kdbx File**
No need to have a database opened.

**Logs**
Please open dev tools in your browser and attach output log from Console tab. If you are using a desktop app, devtools can be opened from Settings/General/Advanced.

>[DEBUG] 2020-11-13T15:00:01.958Z [native-module-connector] Starting native module host
>[ERROR] 2020-11-13T15:00:02.187Z [native-module-connector] Received an error start-usb {"name":"Error","message":"The module '/usr/lib/keeweb/node_modules/@keeweb/keeweb-native-modules/usb-linux-x64.node'\nwas compiled against a different Node.js version using\nNODE_MODULE_VERSION 80. This version of Node.js requires\nNODE_MODULE_VERSION 82. Please try re-compiling or re-installing\nthe module (for instance, using `npm rebuild` or `npm install`).","stack":"Error: The module '/usr/lib/keeweb/node_modules/@keeweb/keeweb-native-modules/usb-linux-x64.node'\nwas compiled against a different Node.js version using\nNODE_MODULE_VERSION 80. This version of Node.js requires\nNODE_MODULE_VERSION 82. Please try re-compiling or re-installing\nthe module (for instance, using `npm rebuild` or `npm install`).\n    at process.func [as dlopen] (electron/js2c/asar.js:140:31)\n    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1196:18)\n    at Object.func [as .node] (electron/js2c/asar.js:140:31)\n    at Module.load (internal/modules/cjs/loader.js:981:32)\n    at Module._load (internal/modules/cjs/loader.js:881:14)\n    at Function.Module._load (electron/js2c/asar.js:769:28)\n    at Module.require (internal/modules/cjs/loader.js:1023:19)\n    at require (internal/modules/cjs/helpers.js:77:18)\n    at reqNative (/usr/lib/keeweb/app.asar/native-module-host.js:172:19)\n    at start-usb (/usr/lib/keeweb/app.asar/native-module-host.js:24:21)"}
>[ERROR] 2020-11-13T15:00:02.598Z [native-module-connector] Host exited with code null and signal SIGSEGV

**Investigations**

The crash comes from the `usb-linux-x64.node` native module. When removing it, no crashes anymore. I didn't investigate further, but I would be able to, if needed.

EDIT: added app log.

**Comment by dr4Ke** [comment]
I should have read the log before doing other investigations. We clearly see that's a node.js version error.

**Comment by dr4Ke** [comment]
Was inconsistency in my package versions.
