### ISSUE TITLE
keeweb-plugin.js not runnable standalone

### ISSUE THREAD

**Issue by Jurrie** [keeweb/keeweb#1665]
**Describe the bug**
On [the wiki](https://github.com/keeweb/keeweb/wiki/Plugins) it states that one can just download [keeweb-plugin.js](https://github.com/keeweb/keeweb/blob/develop/plugins/keeweb-plugin/keeweb-plugin.js) and run it. That's not quite true. The `require('./package.json');` on line 16 breaks.

This is an easy fix: just comment out line 16, and line 45. Then the script can be run using `nodejs keeweb-plugin`.

**To Reproduce**
1. Download [keeweb-plugin.js](https://github.com/keeweb/keeweb/blob/develop/plugins/keeweb-plugin/keeweb-plugin.js) in a new folder
2. Run `nodejs keeweb-plugin.js --help`
3. See the exception:

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/jurrie/Documents/DeesieDjoeks/Keeweb/theme-deesiedjoeks/tmp/keeweb-plugin.js:16:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Expected behavior**
The script runs without error. (Roger that, capt'n Obvious!)

**Environment**
Ubuntu 20.04.01 LTS with nodejs v10.19.0.

**Comment by antelle** [comment]
Thanks, fixed in `develop`
