### ISSUE TITLE
KeeWeb occationaly looses connection to YubiKey

### ISSUE THREAD

**Issue by hadrabap** [keeweb/keeweb#1843]
**Describe the bug**
Sometimes, from time to time, KeeWeb looses connection to YubiKey displaying error code 1. This happens while opening or saving database (any YubiKey challenge/response operation). The YubiKey is permanently present in the USB port. Re-inserting the token does not help.

**To Reproduce**
Steps to reproduce the behavior (for example):
1. Hit the Save button for a database configured for YubiKey challenge/response option
2. An error code 1 is displayed instead of touch request screen

**Expected behavior**
A touch request is presented to the user.

**Additional Details**
It looks like KeeWeb is holding permanent connection to YubiKey. It seems that this situation happens in situations when more YubiKey applications are used as well (PIV, OpenPGP).

There is a [known issue with exclusive locks](https://gpgtools.tenderapp.com/discussions/problems/50028-macgpg2-scdaemon-pcsc-open-failed-sharing-violation-0x8010000b).

I've also discovered that KeePassXC does not have this issue most probably because it [opens and closes YubiKey connection on each occasion](https://github.com/keepassxreboot/keepassxc/blob/2.6.5/src/keys/drivers/YubiKey.cpp#L286-L317).

**Workaround**
1. Restart KeeWeb (potentially looses database changes)
2. run `ykman info` in Terminal and repeat open/save operation in KeeWeb

**Environment**
```
KeeWeb v1.18.6 (070573e, 2021-05-19)
Environment: electron v12.0.7
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)
AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.18.6 Chrome/89.0.4389.128
Electron/12.0.7 Safari/537.36
```

**Kdbx File**
Any YubiKey-secured database.

**Logs**
```
[INFO ] 2021-06-10T13:36:13.549Z [start-profiler] Electron app started in 646ms: loading app requires=5ms, single instance lock=1ms, portable check=0ms, userdata dir=0ms, defining args=19ms, setting env=0ms, app on ready=101ms, loading settings key=26ms, reading app settings=5ms, creating main window=31ms, configuring main window=2ms, restoring main window position=0ms, setting ipc handlers=13ms, setting global shortcuts=0ms, subscribing to power events=0ms, setting request handlers=0ms, main window ready=266ms, main window shown=4ms
[DEBUG] 2021-06-10T13:36:13.557Z [plugin-gallery] Loaded cached plugin gallery 4ms
[INFO ] 2021-06-10T13:36:13.557Z [plugin:theme-thgworks] Loading plugin with resources css (local)
[INFO ] 2021-06-10T13:36:13.561Z [plugin:theme-orange] Loading plugin with resources css (local)
[INFO ] 2021-06-10T13:36:13.562Z [plugin:theme-nord] Loading plugin with resources css (local)
[INFO ] 2021-06-10T13:36:13.562Z [plugin:theme-dracula] Loading plugin with resources css (local)
[INFO ] 2021-06-10T13:36:13.562Z [plugin:theme-darker] Loading plugin with resources css (local)
[INFO ] 2021-06-10T13:36:13.562Z [plugin:theme-cupertino-light] Loading plugin with resources css (local)
[INFO ] 2021-06-10T13:36:13.562Z [plugin:theme-cupertino-dark] Loading plugin with resources css (local)
[INFO ] 2021-06-10T13:36:13.563Z [plugin:theme-cupertino-auto] Loading plugin with resources css (local)
[INFO ] 2021-06-10T13:36:13.563Z [plugin:theme-arc] Loading plugin with resources css (local)
[DEBUG] 2021-06-10T13:36:13.563Z [storage-plugin-files] Load theme-thgworks_plugin.css
[DEBUG] 2021-06-10T13:36:13.564Z [storage-plugin-files] Load theme-orange_plugin.css
[DEBUG] 2021-06-10T13:36:13.564Z [storage-plugin-files] Load theme-nord_plugin.css
[DEBUG] 2021-06-10T13:36:13.564Z [storage-plugin-files] Load theme-dracula_plugin.css
[DEBUG] 2021-06-10T13:36:13.564Z [storage-plugin-files] Load theme-darker_plugin.css
[DEBUG] 2021-06-10T13:36:13.564Z [storage-plugin-files] Load theme-cupertino-light_plugin.css
[DEBUG] 2021-06-10T13:36:13.564Z [storage-plugin-files] Load theme-cupertino-dark_plugin.css
[DEBUG] 2021-06-10T13:36:13.564Z [storage-plugin-files] Load theme-cupertino-auto_plugin.css
[DEBUG] 2021-06-10T13:36:13.564Z [storage-plugin-files] Load theme-arc_plugin.css
[DEBUG] 2021-06-10T13:36:13.565Z [storage-plugin-files] Loaded theme-thgworks_plugin.css 2ms
[DEBUG] 2021-06-10T13:36:13.565Z [plugin:theme-thgworks] Resource data loaded css 8ms
[DEBUG] 2021-06-10T13:36:13.565Z [storage-plugin-files] Loaded theme-orange_plugin.css 2ms
[DEBUG] 2021-06-10T13:36:13.565Z [plugin:theme-orange] Resource data loaded css 4ms
[DEBUG] 2021-06-10T13:36:13.566Z [storage-plugin-files] Loaded theme-nord_plugin.css 2ms
[DEBUG] 2021-06-10T13:36:13.566Z [plugin:theme-nord] Resource data loaded css 4ms
[DEBUG] 2021-06-10T13:36:13.566Z [storage-plugin-files] Loaded theme-dracula_plugin.css 2ms
[DEBUG] 2021-06-10T13:36:13.566Z [plugin:theme-dracula] Resource data loaded css 4ms
[DEBUG] 2021-06-10T13:36:13.566Z [storage-plugin-files] Loaded theme-darker_plugin.css 2ms
[DEBUG] 2021-06-10T13:36:13.566Z [plugin:theme-darker] Resource data loaded css 4ms
[DEBUG] 2021-06-10T13:36:13.566Z [storage-plugin-files] Loaded theme-cupertino-light_plugin.css 2ms
[DEBUG] 2021-06-10T13:36:13.566Z [plugin:theme-cupertino-light] Resource data loaded css 4ms
[DEBUG] 2021-06-10T13:36:13.566Z [storage-plugin-files] Loaded theme-arc_plugin.css 2ms
[DEBUG] 2021-06-10T13:36:13.566Z [plugin:theme-arc] Resource data loaded css 3ms
[DEBUG] 2021-06-10T13:36:13.566Z [storage-plugin-files] Loaded theme-cupertino-dark_plugin.css 2ms
[DEBUG] 2021-06-10T13:36:13.566Z [plugin:theme-cupertino-dark] Resource data loaded css 4ms
[DEBUG] 2021-06-10T13:36:13.567Z [storage-plugin-files] Loaded theme-cupertino-auto_plugin.css 2ms
[DEBUG] 2021-06-10T13:36:13.567Z [plugin:theme-cupertino-auto] Resource data loaded css 4ms
[DEBUG] 2021-06-10T13:36:13.567Z [plugin:theme-thgworks] Resource signature validated css 2ms
[INFO ] 2021-06-10T13:36:13.567Z [plugin:theme-thgworks] Installing plugin resources
[DEBUG] 2021-06-10T13:36:13.568Z [plugin:theme-orange] Resource signature validated css 3ms
[INFO ] 2021-06-10T13:36:13.568Z [plugin:theme-orange] Installing plugin resources
[DEBUG] 2021-06-10T13:36:13.569Z [plugin:theme-nord] Resource signature validated css 4ms
[INFO ] 2021-06-10T13:36:13.569Z [plugin:theme-nord] Installing plugin resources
[DEBUG] 2021-06-10T13:36:13.570Z [plugin:theme-dracula] Resource signature validated css 4ms
[INFO ] 2021-06-10T13:36:13.570Z [plugin:theme-dracula] Installing plugin resources
[DEBUG] 2021-06-10T13:36:13.571Z [plugin:theme-darker] Resource signature validated css 5ms
[INFO ] 2021-06-10T13:36:13.571Z [plugin:theme-darker] Installing plugin resources
[DEBUG] 2021-06-10T13:36:13.571Z [plugin:theme-cupertino-light] Resource signature validated css 5ms
[INFO ] 2021-06-10T13:36:13.571Z [plugin:theme-cupertino-light] Installing plugin resources
[DEBUG] 2021-06-10T13:36:13.572Z [plugin:theme-arc] Resource signature validated css 5ms
[INFO ] 2021-06-10T13:36:13.572Z [plugin:theme-arc] Installing plugin resources
[DEBUG] 2021-06-10T13:36:13.573Z [plugin:theme-cupertino-dark] Resource signature validated css 7ms
[INFO ] 2021-06-10T13:36:13.573Z [plugin:theme-cupertino-dark] Installing plugin resources
[DEBUG] 2021-06-10T13:36:13.574Z [plugin:theme-cupertino-auto] Resource signature validated css 7ms
[INFO ] 2021-06-10T13:36:13.574Z [plugin:theme-cupertino-auto] Installing plugin resources
[DEBUG] 2021-06-10T13:36:13.579Z [plugin:theme-thgworks] Plugin style installed
[INFO ] 2021-06-10T13:36:13.579Z [plugin:theme-thgworks] Install complete 22ms
[DEBUG] 2021-06-10T13:36:13.580Z [plugin:theme-orange] Plugin style installed
[INFO ] 2021-06-10T13:36:13.580Z [plugin:theme-orange] Install complete 19ms
[DEBUG] 2021-06-10T13:36:13.581Z [plugin:theme-nord] Plugin style installed
[INFO ] 2021-06-10T13:36:13.581Z [plugin:theme-nord] Install complete 20ms
[DEBUG] 2021-06-10T13:36:13.582Z [plugin:theme-dracula] Plugin style installed
[INFO ] 2021-06-10T13:36:13.582Z [plugin:theme-dracula] Install complete 20ms
[DEBUG] 2021-06-10T13:36:13.583Z [plugin:theme-darker] Plugin style installed
[INFO ] 2021-06-10T13:36:13.583Z [plugin:theme-darker] Install complete 21ms
[DEBUG] 2021-06-10T13:36:13.585Z [plugin:theme-cupertino-light] Plugin style installed
[INFO ] 2021-06-10T13:36:13.585Z [plugin:theme-cupertino-light] Install complete 22ms
[DEBUG] 2021-06-10T13:36:13.585Z [plugin:theme-arc] Plugin style installed
[INFO ] 2021-06-10T13:36:13.586Z [plugin:theme-arc] Install complete 23ms
[DEBUG] 2021-06-10T13:36:13.587Z [plugin:theme-cupertino-dark] Plugin style installed
[INFO ] 2021-06-10T13:36:13.587Z [plugin:theme-cupertino-dark] Install complete 25ms
[DEBUG] 2021-06-10T13:36:13.589Z [plugin:theme-cupertino-auto] Plugin style installed
[INFO ] 2021-06-10T13:36:13.589Z [plugin:theme-cupertino-auto] Install complete 27ms
[INFO ] 2021-06-10T13:36:13.589Z [plugin-mgr] Loaded 9 plugins 38ms
[DEBUG] 2021-06-10T13:36:13.590Z [settings-manager] Theme changed light
[INFO ] 2021-06-10T13:36:13.591Z [usb-listener] Starting USB listener
[DEBUG] 2021-06-10T13:36:13.591Z [native-module-connector] Starting native module host
[INFO ] 2021-06-10T13:36:13.666Z [start-profiler] App started in 421ms: fetching=135ms, pre-init=195ms, loading modules=76ms, document ready=11ms, creating app model=2ms, loading configs=20ms, initializing modules=39ms, loading remote config=1ms, checking features=0ms, initializing storage=0ms, starting usb=0ms, first view rendering=75ms, app ready event=0ms
[DEBUG] 2021-06-10T13:36:13.716Z [usb-listener] YubiKeys changed 0 => 1
[INFO ] 2021-06-10T13:36:14.170Z [updater] Next update check will happen in 69197s
[INFO ] 2021-06-10T13:36:14.173Z [browser-extension-connector] Started
[INFO ] 2021-06-10T13:36:15.303Z [open:Secure Store] File open request
[INFO ] 2021-06-10T13:36:15.303Z [open:Secure Store] Open file from storage file
[INFO ] 2021-06-10T13:36:15.303Z [open:Secure Store] Stat file
[DEBUG] 2021-06-10T13:36:15.303Z [storage-file] Stat /Users/petr/sync-folder/Secure Store.kdbx
[DEBUG] 2021-06-10T13:36:15.304Z [storage-file] Stat done /Users/petr/sync-folder/Secure Store.kdbx 1ms
[INFO ] 2021-06-10T13:36:15.304Z [open:Secure Store] Open file from storage (1623324816643, local 1623324816643)
[INFO ] 2021-06-10T13:36:15.304Z [open:Secure Store] Load from storage
[DEBUG] 2021-06-10T13:36:15.304Z [storage-file] Load /Users/petr/sync-folder/Secure Store.kdbx
[DEBUG] 2021-06-10T13:36:15.327Z [storage-file] Loaded /Users/petr/sync-folder/Secure Store.kdbx 1623324816643 23ms
[INFO ] 2021-06-10T13:36:15.327Z [open:Secure Store] Open file from content loaded from storage
[DEBUG] 2021-06-10T13:36:15.331Z [chal-resp] Calculating ChalResp using a YubiKey {"vid":4176,"pid":1031,"serial":XXXXXXXX,"slot":1}
[ERROR] 2021-06-10T13:36:15.347Z [chal-resp] YubiKey ChalResp error {"name":"Error","message":"USB error in yk_open_key_vid_pid: kIOReturnBadArgument","stack":"Error: USB error in yk_open_key_vid_pid: kIOReturnBadArgument","code":1,"ykError":true}
[ERROR] 2021-06-10T13:36:15.348Z [file] Error opening file 1 USB error in yk_open_key_vid_pid: kIOReturnBadArgument {"name":"Error","message":"USB error in yk_open_key_vid_pid: kIOReturnBadArgument","stack":"Error: USB error in yk_open_key_vid_pid: kIOReturnBadArgument","code":1,"ykError":true}
[ERROR] 2021-06-10T13:36:15.348Z [open-view] Error opening file {"name":"Error","message":"USB error in yk_open_key_vid_pid: kIOReturnBadArgument","stack":"Error: USB error in yk_open_key_vid_pid: kIOReturnBadArgument","code":1,"ykError":true}
```

**Comment by antelle** [comment]
What happens if you run 
```
ykman otp calculate 2 010203
```
in this state?

**Comment by hadrabap** [comment]
Hello,

Will do so, when it happens.

Now everything works and the `ykman otp calculate` works only under the `root` user:
```
localhost:~ petr$ /usr/local/bin/ykman otp calculate 1 010203 
Traceback (most recent call last):
  File "/usr/local/bin/ykman", line 8, in <module>
    sys.exit(main())
  File "/opt/local/yubikey/lib/python3.9/site-packages/ykman/cli/__main__.py", line 371, in main
    cli(obj={})
  File "/opt/local/yubikey/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/local/yubikey/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/local/yubikey/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/local/yubikey/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/local/yubikey/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/local/yubikey/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/local/yubikey/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/local/yubikey/lib/python3.9/site-packages/ykman/cli/otp.py", line 602, in calculate
    session = ctx.obj["session"]
  File "/opt/local/yubikey/lib/python3.9/site-packages/ykman/cli/util.py", line 164, in __getitem__
    self.resolve()
  File "/opt/local/yubikey/lib/python3.9/site-packages/ykman/cli/util.py", line 161, in resolve
    self._objects[k] = f()
  File "/opt/local/yubikey/lib/python3.9/site-packages/ykman/cli/__main__.py", line 299, in <lambda>
    ctx.obj.add_resolver("conn", lambda: resolve()[0])
  File "/opt/local/yubikey/lib/python3.9/site-packages/ykman/cli/__main__.py", line 294, in resolve
    items = _run_cmd_for_single(ctx, subcmd.name, connections, reader)
  File "/opt/local/yubikey/lib/python3.9/site-packages/ykman/cli/__main__.py", line 190, in _run_cmd_for_single
    return retrying_connect(None, connections, state=state)
  File "/opt/local/yubikey/lib/python3.9/site-packages/ykman/cli/__main__.py", line 88, in retrying_connect
    return connect_to_device(serial, connections)
  File "/opt/local/yubikey/lib/python3.9/site-packages/ykman/device.py", line 216, in connect_to_device
    conn = dev.open_connection(connection_type)
  File "/opt/local/yubikey/lib/python3.9/site-packages/ykman/hid/base.py", line 50, in open_connection
    return self._connection_cls(self.path)
  File "/opt/local/yubikey/lib/python3.9/site-packages/ykman/hid/macos.py", line 185, in __init__
    raise OSError(f"Failed to open device for communication: {result}")
OSError: Failed to open device for communication: -536870206

localhost:~ petr$ sudo /usr/local/bin/ykman otp calculate 1 010203
Touch your YubiKey...
<<<hash>>>

localhost:~ petr$ sudo /usr/local/bin/ykman otp calculate 2 010203
Error: Failed to write to the YubiKey. Make sure the device does not have restricted access.
```

NB: In my case I have the OTP application in Slot # 1. The Challenge/Response used by KeeWeb is deployed in Slot # 2.

Anyway, I'll perform the same when KeeWeb looses connection to my YubiKey.

Thanks in advance!

**Comment by hadrabap** [comment]
> What happens if you run
> 
> ```
> ykman otp calculate 2 010203
> ```
> 
> in this state?

Hello,

Happened right now.

I ran 
```
localhost:~ petr$ sudo /usr/local/bin/ykman otp calculate 1 010203
Touch your YubiKey...
<hash>
```
and it worked.

By consequent it fixed KeeWeb as well. It seems that establishing any kind of communication with YubiKey using `ykman` fixes the issue. Exactly as I described in the _Workaround_ section.

**Comment by antelle** [comment]
Ok, thank you for the detailed description! I'll try to reproduce it.
