### ISSUE TITLE
desktop app argon2d decode error

### ISSUE THREAD

**Issue by Traine9** [keeweb/keeweb#1949]
**Describe the bug**
argon2d decode error

**To Reproduce**
1. create new kdbx4 file in webapp
2. with params: 
iterations: 20,
Memory, KB: 100000
Parallelism: 2
3.download file and try to open it with desktop app 1.18.7 on ubuntu 16.04.7 LTS

**Expected behavior**
open file

**Screenshots**

**Environment**
KeeWeb v1.18.7 (dfc6201, 2021-07-18)
Environment: electron v12.0.7
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.18.7 Chrome/89.0.4389.128 Electron/12.0.7 Safari/537.36

**Kdbx File**
not need

**Logs**
[ERROR] 2021-12-09T15:45:48.271Z [open-view] Error opening file {"name":"Error","message":"/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/share/keeweb-desktop/resources/node_modules/@keeweb/keeweb-native-modules/argon2-linux-x64.node)","stack":"Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/share/keeweb-desktop/resources/node_modules/@keeweb/keeweb-native-modules/argon2-linux-x64.node)\n    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)\n    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)\n    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)\n    at Module.load (internal/modules/cjs/loader.js:935:32)\n    at Module._load (internal/modules/cjs/loader.js:776:14)\n    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)\n    at Module.require (internal/modules/cjs/loader.js:959:19)\n    at require (internal/modules/cjs/helpers.js:88:18)\n    at reqNative (/usr/share/keeweb-desktop/resources/app.asar/scripts/util/req-native.js:21:19)\n    at argon2 (/usr/share/keeweb-desktop/resources/app.asar/native-module-host.js:83:24)"}

**Comment by antelle** [comment]
Try installing this glibc version

**Comment by antelle** [comment]
did this help?
