### ISSUE TITLE
Unable to connect, Brave browser, Ubuntu 20.04

### ISSUE THREAD

**Issue by scottresnik** [keeweb/keeweb#2011]
Hello,

I'm attempting to connect Keeweb Connect with the Brave browser.  I have followed most of the suggestions on #1810 but am still not able to connect.

I receive the following in the console of the background page of the extension:
```
Connecting to KeeWeb
background.js:692 -> KW {action: 'change-public-keys', extensionName: 'KeeWeb Connect', version: '0.3.7', publicKey: '****', nonce: '*****', …} action: "change-public-keys"clientID: "mQ8eJ4ZdCrFODjr0FcVPR2U8bvYE3HpM"extensionName: "KeeWeb Connect"nonce: "****" publicKey: "****"version: "0.3.7"[[Prototype]]: Object
background.js:1468 KeeWeb host disconnected Specified native messaging host not found.
background.js:644 KeeWeb disconnected
background.js:621 Connect error Error: Cannot connect to KeeWeb, please check if KeeWeb is open and browser integration is enabled in settings.
    at Backend.rejectPendingRequests (background.js:715:21)
    at TransportNativeMessaging.<anonymous> (background.js:655:18)
    at TransportNativeMessaging.emit (background.js:160:5)
    at TransportNativeMessaging.portDisconnected (background.js:1469:18)
    at background.js:1445:56
```

I am able to use Google Chrome successfully.  KeeWeb native is open and both Chrome, and "Other Browsers" check boxes are checked.

When I follow [this suggestion](https://github.com/keeweb/keeweb/issues/1810#issuecomment-835842527) I get the expected results.

My `~/.config/chromium/NativeMessagingHosts/net.antelle.keeweb.keeweb_connect.json` is as follows:

```
{
    "allowed_origins": [
        "chrome-extension://pikpfmjfkekaeinceagbebpfkmkdlcjk/"
    ],
    "description": "KeeWeb native messaging host",
    "name": "net.antelle.keeweb.keeweb_connect",
    "type": "stdio",
    "path": "/usr/share/keeweb-desktop/keeweb-native-messaging-host"
}
```

What else should I check to make this work?  Thanks for any help you can offer.

**Comment by fabiiretro** [comment]
You have to copy net.antelle.keeweb.keeweb_connect.json to your config folder for Brave. In my case, using the .rpm of keeweb, it created the file in ~/.config/google-chrome. If the command below does not work for you, try looking for the file in there, as well.

`cp ~/.config/chromium/NativeMessagingHosts/net.antelle.keeweb.keeweb_connect.json ~/.config/BraveSoftware/Brave-Browser-Beta/NativeMessagingHosts/`

**Comment by scottresnik** [comment]
Thanks @fabiiretro .  This fixed my issue.
