### ISSUE TITLE
Error on version 1.3.1 on OSX 10.11.4

### ISSUE THREAD

**Issue by PercussiveRepair** [keeweb/keeweb#349]
Since updating to 1.3.1 on mac I get the periodic error window: 
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'webContents' of null
    at emitBackboneEvent (/Users/user/Library/Application Support/KeeWeb/app.js:230:15)
    at EventEmitter.electron.powerMonitor.on (/Users/user/Library/Application Support/KeeWeb/app.js:299:9)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)

The app seems to be performing correctly. I haven't noticed any issues with saving new/updated entries.

**Comment by antelle** [comment]
fixed, will be available soon, let's wait a bit for other bugfixes...

**Comment by StuStirling** [comment]
I have the same kind of thing, different stack trace to the above though. Running KeeWeb Version 1.3.1 (234333d) on Mac OS X 10.11.6

```
Uncaught Exception:
TypeError: Cannot read property 'webContents' of null
    at emitBackboneEvent (/Applications/KeeWeb.app/Contents/Resources/app/app.js:230:15)
    at PowerMonitor.electron.powerMonitor.on (/Applications/KeeWeb.app/Contents/Resources/app/app.js:299:9)
    at emitOne (events.js:96:13)
    at PowerMonitor.emit (events.js:188:7)
```

**Comment by antelle** [comment]
Please test v1.3.2, it should have been already fixed

**Comment by StuStirling** [comment]
Great sorry, just seen the update. If you don't hear from me it's been fixed 👍
