### ISSUE TITLE
Uncaught: Cannot create BrowserWindow before app is ready

### ISSUE THREAD

**Issue by cema-sp** [keeweb/keeweb#431]
Hi, I got an exception opening KeeWeb from MacOS Doc panel (App Opened but with an exception):

~~~js
Uncaught Exception:
Error: Cannot create BrowserWindow before app is ready
    at Error (native)
    at createMainWindow (/Users/cema-sp/Library/Application Support/KeeWeb/app.js:110:18)
    at EventEmitter.app.on (/Users/cema-sp/Library/Application Support/KeeWeb/app.js:58:13)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
~~~

- what were your actions?

  Opened App from Mac OS Doc panel

- what was wrong?

  Application opened, but I got an exception.

- app version

  KeeWeb v.1.3.3

- your user-agent (from Settings/Help section)

  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) 

- does it happen on Demo or New database?

  My previously used DB (from Google Drive)

- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)

  ~~~js
  index.html:13 2016-11-07T07:58:04.627Z [updater] Next update check will happen in 1s
  index.html:13 2016-11-07T07:58:05.128Z [updater] Checking for update...
  index.html:13 2016-11-07T07:58:05.128Z [transport] GET   https://app.keeweb.info/manifest.appcache
  index.html:13 2016-11-07T07:58:05.146Z [transport] Request to   https://app.keeweb.info/manifest.appcache without proxy
  index.html:13 2016-11-07T07:58:05.700Z [transport] Response from   https://app.keeweb.info/manifest.appcache: 200
  index.html:13 2016-11-07T07:58:05.703Z [updater] Update check: # 2016-09-20:v1.3.3
  index.html:13 2016-11-07T07:58:05.707Z [updater] Next update check will happen in 86400s
  ~~~

**Comment by antelle** [comment]
release published
