### ISSUE TITLE
Issue with WebDav

### ISSUE THREAD

**Issue by LiloBzH** [keeweb/keeweb#877]
- what were your actions? Sync with Webdav and Owncloud
- what was wrong? Erreur 500 . Keeweb send a request with url : file://
- app version 1.6.3 (windows)
- does it happen on Demo or New database? all
- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)

```
[DEBUG] 2018-02-27T08:40:33.178Z [storage-webdav] Save:put error https://cloud.blop.com/remote.php/dav/files/blop/.blop.kdbx.4851678186768 500 337ms
[INFO ] 2018-02-27T08:40:33.178Z [sync:Lilo] Error saving data to storage
[INFO ] 2018-02-27T08:40:33.179Z [sync:Lilo] Sync finished HTTP status 500
```
Ticket Owncloud here : https://github.com/owncloud/core/issues/30330 but we think the problem is Keeweb.

Keeweb seems bo be send local URL first and after remote url

first : file://
2nd : https://cloud.blop.com/remote.php/dav/files/blop/.coucou.1519646962149
3rd : file://
4 : https://cloud.blop.com/remote.php/dav/files/blop/.coucou.1519646962149

**Comment by antelle** [comment]
Hi! This is a problem with your webserver, somehow it returns status 500. You can go to server logs to check what's happening.

**Comment by LiloBzH** [comment]
are you serious ?

If i open a ticket, it's not a problem of webserver. Can you read my ticket ?

**Comment by antelle** [comment]
So, what's the problem in keeweb? You get 500 from your server. Did you figure out, why? We send an incorrect url, or what happens?

**Comment by LiloBzH** [comment]
Webdav Synology <-> OWncloud is OK. No problem.

log of owncloud

`{"reqId":"PNxKInIc0GRaAtBrPuYg","level":3,"time":"2018-01-31T17:58:01+00:00","remoteAddr":"123.123.123.123","user":"Tom","app":"remote","method":"PUT","url":"\/remote.php\/dav\/files\/tom\/Keepass\/.tom.kdbx.1517421479927","message":"Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"Invalid url \\\"file:\\\/\\\/\\\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/Util.php(805): OCP\\\\Util::getFullDomain('file:\\\/\\\/')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/CorsPlugin.php(71): OCP\\\\Util::isSameDomain('file:\\\/\\\/', 'https:\\\/\\\/cloud.d...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(407): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\CorsPlugin->initialize(Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Server))\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(93): Sabre\\\\DAV\\\\Server->addPlugin(Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\CorsPlugin))\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->__construct(Object(OC\\\\AppFramework\\\\Http\\\\Request), '\\\/remote.php\\\/dav...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/Util.php\",\"Line\":768}"}`


Read : **Invalid url \\\"file:\\\/\\\/\\\**

First, keeweb seems to send 1st an bad url ( file:// )

Error 500 of owncloud because of course, url "file://" is not possible.
Owncloud receives request with this paramters.

After this first request, Owncloud received good url.

**Comment by antelle** [comment]
What is `file://`? I don't know what's get written in ownCloud logs, could you please paste what's sent to the server? E.g. from Network panel in devtools of your browser. If you're using a desktop apps, devtools are in Settings > General.

**Comment by LiloBzH** [comment]
all log are in this post

Snif with Fiddler

```
PUT https://cloud.blop.com/remote.php/dav/files/blop/Keepass/.blop.kdbx.8498789165874987 HTTP/1.1
Host: cloud.blop.com
Connection: keep-alive
Content-Length: 204766
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.6.3 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36
# Origin: file://
X-DevTools-Request-Id: 10172.315
Authorization: Basic bGlsb2J6aqsd894sq98d7qsdDQ1Ng==
Content-Type: application/octet-stream
Accept: */*
Accept-Encoding: gzip, deflate
```

maybe ?

**Comment by antelle** [comment]
This contradicts with what you said above about `file://`, this request seems to be perfectly normal. Does it return 500?

**Comment by antelle** [comment]
I spotted also this:
```
# Origin: file://
```
Probably it causes owncloud to fail inside origin check.

**Comment by LiloBzH** [comment]
This request return 500 . 

Why there is in line 6 "Origin: file://"

**Comment by antelle** [comment]
It can include origin:file, as if the file was opened locally. Do you know why there's a hash (`#`) before origin? It seems a bit strange.

**Comment by LiloBzH** [comment]
I Fw because Owncloud say it's keeweb problem and You said it's Owncloud problem so :-(

For the # => I wanted to put in bold ^^

**Comment by antelle** [comment]
This seems to be a problem in keeweb, however some servers can accept this origin. It's better to fix it.

**Comment by LiloBzH** [comment]
ahh !! Thank you for watching ! Cool :)

**Comment by pwFoo** [comment]
I can't save to webdav until I changed keeweb config to write kdbx with put instead of temp file.
But at the moment I can save / sync changes, but client doesn't update the file from webdav?

Follow here because of webdav related problem I'm interested in and I'll open a new issue because keeweb client isn't reload / update file.

**Comment by LiloBzH** [comment]
Thank's for upgrade. It's ok now :)
